test_cart: &id001
- test_click_buy_allterm_day.parquet
- test_click_buy_allterm_hour.parquet
- test_click_buy_allterm_last.parquet
- test_click_buy_allterm_top.parquet
- test_click_buy_base_day.parquet
- test_click_buy_base_hour.parquet
- test_click_buy_base_hour_day.parquet
- test_click_buy_base_hour_hour.parquet
- test_click_buy_base_hour_last.parquet
- test_click_buy_base_hour_top.parquet
- test_click_buy_base_last.parquet
- test_click_buy_base_top.parquet
- test_click_buy_base_wlen_day.parquet
- test_click_buy_base_wlen_hour.parquet
- test_click_buy_base_wlen_last.parquet
- test_click_buy_base_wlen_top.parquet
- test_click_buy_dup_day.parquet
- test_click_buy_dup_hour.parquet
- test_click_buy_dup_hour_hour.parquet
- test_click_buy_dup_hour_last.parquet
- test_click_buy_dup_last.parquet
- test_click_buy_dup_top.parquet
- test_click_buy_dup_wlen_day.parquet
- test_click_buy_dup_wlen_hour.parquet
- test_click_buy_dup_wlen_last.parquet
- test_click_buy_dup_wlen_top.parquet
- test_click_click_allterm_day.parquet
- test_click_click_allterm_hour.parquet
- test_click_click_allterm_last.parquet
- test_click_click_allterm_top.parquet
- test_click_click_base_day.parquet
- test_click_click_base_hour.parquet
- test_click_click_base_hour_day.parquet
- test_click_click_base_hour_hour.parquet
- test_click_click_base_hour_last.parquet
- test_click_click_base_hour_top.parquet
- test_click_click_base_last.parquet
- test_click_click_base_top.parquet
- test_click_click_base_wlen_day.parquet
- test_click_click_base_wlen_hour.parquet
- test_click_click_base_wlen_last.parquet
- test_click_click_base_wlen_top.parquet
- test_click_click_dup_day.parquet
- test_click_click_dup_hour.parquet
- test_click_click_dup_hour_hour.parquet
- test_click_click_dup_hour_last.parquet
- test_click_click_dup_last.parquet
- test_click_click_dup_top.parquet
- test_click_click_dup_wlen_day.parquet
- test_click_click_dup_wlen_hour.parquet
- test_click_click_dup_wlen_last.parquet
- test_click_click_dup_wlen_top.parquet
- test_buy_buy_allterm_all.parquet
- test_buy_buy_base_all.parquet
- test_buy_buy_base_hour_all.parquet
- test_buy_buy_base_wlen_all.parquet
- test_buy_buy_dup_all.parquet
- test_buy_buy_dup_hour_all.parquet
- test_buy_buy_dup_wlen_all.parquet
- test_buy_click_allterm_all.parquet
- test_buy_click_base_all.parquet
- test_buy_click_base_hour_all.parquet
- test_buy_click_base_wlen_all.parquet
- test_buy_click_dup_all.parquet
- test_buy_click_dup_hour_all.parquet
- test_buy_click_dup_wlen_all.parquet
test_click: *id001
test_click_all: *id001
test_order: *id001
train_cart: &id002
- train_click_buy_allterm_day.parquet
- train_click_buy_allterm_hour.parquet
- train_click_buy_allterm_last.parquet
- train_click_buy_allterm_top.parquet
- train_click_buy_base_day.parquet
- train_click_buy_base_hour.parquet
- train_click_buy_base_hour_day.parquet
- train_click_buy_base_hour_hour.parquet
- train_click_buy_base_hour_last.parquet
- train_click_buy_base_hour_top.parquet
- train_click_buy_base_last.parquet
- train_click_buy_base_top.parquet
- train_click_buy_base_wlen_day.parquet
- train_click_buy_base_wlen_hour.parquet
- train_click_buy_base_wlen_last.parquet
- train_click_buy_base_wlen_top.parquet
- train_click_buy_dup_day.parquet
- train_click_buy_dup_hour.parquet
- train_click_buy_dup_hour_hour.parquet
- train_click_buy_dup_hour_last.parquet
- train_click_buy_dup_last.parquet
- train_click_buy_dup_top.parquet
- train_click_buy_dup_wlen_day.parquet
- train_click_buy_dup_wlen_hour.parquet
- train_click_buy_dup_wlen_last.parquet
- train_click_buy_dup_wlen_top.parquet
- train_click_click_allterm_day.parquet
- train_click_click_allterm_hour.parquet
- train_click_click_allterm_last.parquet
- train_click_click_allterm_top.parquet
- train_click_click_base_day.parquet
- train_click_click_base_hour.parquet
- train_click_click_base_hour_day.parquet
- train_click_click_base_hour_hour.parquet
- train_click_click_base_hour_last.parquet
- train_click_click_base_hour_top.parquet
- train_click_click_base_last.parquet
- train_click_click_base_top.parquet
- train_click_click_base_wlen_day.parquet
- train_click_click_base_wlen_hour.parquet
- train_click_click_base_wlen_last.parquet
- train_click_click_base_wlen_top.parquet
- train_click_click_dup_day.parquet
- train_click_click_dup_hour.parquet
- train_click_click_dup_hour_hour.parquet
- train_click_click_dup_hour_last.parquet
- train_click_click_dup_last.parquet
- train_click_click_dup_top.parquet
- train_click_click_dup_wlen_day.parquet
- train_click_click_dup_wlen_hour.parquet
- train_click_click_dup_wlen_last.parquet
- train_click_click_dup_wlen_top.parquet
- train_buy_buy_allterm_all.parquet
- train_buy_buy_base_all.parquet
- train_buy_buy_base_hour_all.parquet
- train_buy_buy_base_wlen_all.parquet
- train_buy_buy_dup_all.parquet
- train_buy_buy_dup_hour_all.parquet
- train_buy_buy_dup_wlen_all.parquet
- train_buy_click_allterm_all.parquet
- train_buy_click_base_all.parquet
- train_buy_click_base_hour_all.parquet
- train_buy_click_base_wlen_all.parquet
- train_buy_click_dup_all.parquet
- train_buy_click_dup_hour_all.parquet
- train_buy_click_dup_wlen_all.parquet
train_click: *id002
train_click_all: *id002
train_order: *id002
